### ISSUE TITLE
Will this ever get updated again?

### ISSUE THREAD

**Issue by ThatGuyCalledJesse** [jslater89/OpenTafl#3]
It was such a good idea, it got me interested in making a RL model that plays the game

**Comment by jslater89** [comment]
While there are still improvements to be made in terms of AI, I think the project is more or less done in terms of core function: it can run tafl games according to almost any ruleset, it can host multiplayer games, it can run external engines, and the protocols for those features are well specified.

I'm open to revisiting it at some point in the unspecified future if there are open issues, but otherwise I'm pretty pleased with the state it's it.
